### ISSUE TITLE
cannot return value obtained from unexported field or method

### ISSUE THREAD

**Issue by sevenval-admins** [Myra-Security-GmbH/myra-shell#1]
While trying to build the current version an error occurs upon starting the compiled software:

```
root@33e280fd38f9:/go/src/myra-shell# go version
go version go1.13.6 linux/amd64

root@33e280fd38f9:/go/src/myra-shell# make -v
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu

# make build
go get .
rm -f myra-shell
go build -ldflags="-s -w" -o myra-shell ./main.go

# ./myra-shell
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x81c340, 0xc2b858, 0x1b8, 0x962e01, 0x81c340, 0xc00025a609)
	/usr/local/go/src/reflect/value.go:1014 +0x1bc
reflect.Value.Interface(...)
	/usr/local/go/src/reflect/value.go:1003
github.com/alexflint/go-arg.isZero(0x81c340, 0xc2b858, 0x1b8, 0x1)
	/go/src/github.com/alexflint/go-arg/parse.go:757 +0x18c
github.com/alexflint/go-arg.NewParser(0x0, 0x0, 0xc0001d9f40, 0x1, 0x1, 0x19, 0x817d80, 0x5)
	/go/src/github.com/alexflint/go-arg/parse.go:213 +0x5af
github.com/alexflint/go-arg.MustParse(0xc0001d9f40, 0x1, 0x1, 0x40d666)
	/go/src/github.com/alexflint/go-arg/parse.go:82 +0x54
main.main()
	/go/src/myra-shell/main.go:128 +0x83

# make test
go test $(go list ./... | grep -v "/vendor/")
# myra-shell/api/authentication
package myra-shell/api/authentication (test)
	imports github.com/stretchr/testify/require: cannot find package "github.com/stretchr/testify/require" in any of:
	/usr/local/go/src/github.com/stretchr/testify/require (from $GOROOT)
	/go/src/github.com/stretchr/testify/require (from $GOPATH)
FAIL	myra-shell/api/authentication [setup failed]
# myra-shell/command
package myra-shell/api/authentication (test)
	imports github.com/stretchr/testify/require: cannot find package "github.com/stretchr/testify/require" in any of:
	/usr/local/go/src/github.com/stretchr/testify/require (from $GOROOT)
	/go/src/github.com/stretchr/testify/require (from $GOPATH)
FAIL	myra-shell/command [setup failed]
# myra-shell/config
package myra-shell/api/authentication (test)
	imports github.com/stretchr/testify/require: cannot find package "github.com/stretchr/testify/require" in any of:
	/usr/local/go/src/github.com/stretchr/testify/require (from $GOROOT)
	/go/src/github.com/stretchr/testify/require (from $GOPATH)
FAIL	myra-shell/config [setup failed]
# myra-shell/context
package myra-shell/api/authentication (test)
	imports github.com/stretchr/testify/require: cannot find package "github.com/stretchr/testify/require" in any of:
	/usr/local/go/src/github.com/stretchr/testify/require (from $GOROOT)
	/go/src/github.com/stretchr/testify/require (from $GOPATH)
FAIL	myra-shell/context [setup failed]
# myra-shell/storage
package myra-shell/api/authentication (test)
	imports github.com/stretchr/testify/require: cannot find package "github.com/stretchr/testify/require" in any of:
	/usr/local/go/src/github.com/stretchr/testify/require (from $GOROOT)
	/go/src/github.com/stretchr/testify/require (from $GOPATH)
FAIL	myra-shell/storage [setup failed]
?   	myra-shell	[no test files]
?   	myra-shell/api	[no test files]
?   	myra-shell/api/types	[no test files]
?   	myra-shell/api/vo	[no test files]
?   	myra-shell/command/impl	[no test files]
?   	myra-shell/command/impl/listing	[no test files]
?   	myra-shell/console	[no test files]
?   	myra-shell/container	[no test files]
?   	myra-shell/event	[no test files]
?   	myra-shell/eventHandler	[no test files]
?   	myra-shell/output	[no test files]
?   	myra-shell/tag	[no test files]
?   	myra-shell/util	[no test files]
FAIL
make: *** [Makefile:39: test] Error 1
```

**Comment by hakankpunkt** [comment]
Running make and then make test works on Debian Buster:

```
hakan@x1-carbon:~/go/src/myra-shell$ go version
go version go1.11.6 linux/amd64
```

```
hakan@x1-carbon:~/go/src/myra-shell$ make -v
GNU Make 4.2.1
```

`hakan@x1-carbon:~/go/src$ git clone https://github.com/Myra-Security-GmbH/myra-shell.git  `                                                                                                                                

`hakan@x1-carbon:~/go/src$ cd myra-shell/`

```
hakan@x1-carbon:~/go/src/myra-shell$ make
dep ensure
rm -f myra-shell
go build -ldflags="-s -w" -o myra-shell ./main.go
hakan@x1-carbon:~/go/src/myra-shell$
```

```
hakan@x1-carbon:~/go/src/myra-shell$ ./myra-shell
Creating config file
```



hakan@x1-carbon:~/go/src/myra-shell$ make test
```
go test $(go list ./... | grep -v "/vendor/")
?       myra-shell      [no test files]
?       myra-shell/api  [no test files]
ok      myra-shell/api/authentication   0.049s
?       myra-shell/api/types    [no test files]
?       myra-shell/api/vo       [no test files]
ok      myra-shell/command      0.078s
?       myra-shell/command/impl [no test files]
?       myra-shell/command/impl/listing [no test files]
ok      myra-shell/config       0.057s
?       myra-shell/console      [no test files]
?       myra-shell/container    [no test files]
ok      myra-shell/context      0.030s
?       myra-shell/event        [no test files]
?       myra-shell/eventHandler [no test files]
?       myra-shell/output       [no test files]
ok      myra-shell/storage      0.031s
?       myra-shell/tag  [no test files]
?       myra-shell/util [no test files]
```

**Comment by sevenval-admins** [comment]
I was running a docker container 'golang:latest' while building this. Reading your comment I also tried to use 'debian:latest' in which I had to install make+golang first prior running the commands.  I ran into the same issue here!

Maybe you can provide a Dockerfile for reference on how to get this software up an running. I'm really not an expert on compiling go projects  ;-) Thank you

**Comment by hakankpunkt** [comment]
Can you please test again after a fresh pull?

**Comment by sevenval-admins** [comment]
I re-tested with a golang docker container and now everthing works including 'make test' and 'make build'.  👍
